{"name": "test_create_user_normal", "status": "failed", "statusDetails": {"message": "AssertionError: Expected 200, got 404", "trace": "self = <test_create_user.TestCreateUser object at 0x0000021ED4973ED0>\n\n    @allure.story(\"Create user with valid details\")\n    def test_create_user_normal(self):\n        api = UserAPI()\n        username = random_username()\n        email = random_email()\n        res = api.create_user(username, email, \"123456\")\n>       assert_response(res, 200)\n\ntestcases\\test_create_user.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nresponse = <Response [404]>, expected_code = 200\n\n    def assert_response(response, expected_code=200):\n>       assert response.status_code == expected_code, f\"Expected {expected_code}, got {response.status_code}\"\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nE       AssertionError: Expected 200, got 404\n\ncommon\\assertions.py:2: AssertionError"}, "start": 1760199705015, "stop": 1760199706523, "uuid": "9590f77a-4b2b-4a65-9fc1-5583e3297f3d", "historyId": "d6dcabd8926a19a5b703625804d44952", "testCaseId": "d6dcabd8926a19a5b703625804d44952", "fullName": "testcases.test_create_user.TestCreateUser#test_create_user_normal", "labels": [{"name": "feature", "value": "Create User API"}, {"name": "story", "value": "Create user with valid details"}, {"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "DESKTOP-AC1JF6R"}, {"name": "thread", "value": "8276-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_create_user"}], "titlePath": ["testcases", "test_create_user.py", "TestCreateUser"]}